---
title: "Formulae for Math Econ 1"
author:
- name: Robert Ayerton Bailey Smith
  affiliation: Aalborg University
  email: rs@business.aau.dk
date: "`r format(Sys.time(), '%B %d, %Y (%H:%M)')`"
urlcolor: blue
output:
  bookdown::pdf_document2:
    citation_package: natbib
    fig_caption: yes
    dev: tikz
    keep_tex: yes
    number_sections: yes
    toc: no
  bookdown::gitbook:
    config:
      toc:
        collapse: section
    self.contained: yes
    split_by: none
  bookdown::html_document2: default
bibliography: Bibliography.bib
biblio-style: apalike
header-includes: 
  - \usepackage{tikz}
  - \usepackage{pgfplots}
  - \usepackage{fontawesome5}
  - \usepackage{academicons}
  - \usetikzlibrary{calc,matrix}
  - \newcommand{\myunit}{1 cm}
  - \tikzset{
    node style sp/.style={draw,circle,minimum size=\myunit},
    node style ge/.style={circle,minimum size=\myunit},
    arrow style mul/.style={draw,sloped,midway,fill=white},
    arrow style plus/.style={midway,sloped,fill=white},}
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Formulae

## Vector addition rules, and scalar-vector multiplication rules

If $\mathbf{a}$, $\mathbf{b}$ and $\mathbf{c}$ are arbitrary *n*-vectors and $\alpha$, $\beta$ are arbitrary numbers, then:

a. $(\mathbf{a} + \mathbf{b}) + \mathbf{c} = \mathbf{a} + (\mathbf{b} + \mathbf{c})$
b. $\mathbf{a} + \mathbf{b}  = \mathbf{b} + \mathbf{a}$
c. $\mathbf{a} + \mathbf{0}  = \mathbf{a}$
d. $\mathbf{a} + (-\mathbf{a})  = \mathbf{0}$
e. $(\alpha + \beta)\mathbf{a} = \alpha\mathbf{a} + \beta\mathbf{a}$
f. $\alpha(\mathbf{a} + \mathbf{b})  = \alpha\mathbf{a} + \alpha\mathbf{b}$
g. $\alpha(\beta\mathbf{a}) = (\alpha\beta)\mathbf{a}$
h. $1\mathbf{a} = \mathbf{a}$

## Vector and scalar product rules
a. $\mathbf{a} \cdot \mathbf{b} = \mathbf{b} \cdot \mathbf{a}$
b. $\mathbf{a} \cdot (\mathbf{b} + \mathbf{c})  = \mathbf{a}\cdot \mathbf{b} + \mathbf{a}\cdot\mathbf{c}$
c. $(\alpha\mathbf{a})\cdot \mathbf{b} = \mathbf{a} \cdot (\alpha\mathbf{b}) = \alpha (\mathbf{a}\cdot\mathbf{b})$
d. $\mathbf{a}\cdot\mathbf{a} > 0 \Longleftrightarrow \mathbf{a}\neq \mathbf{0}$

## Transpose Rules
a. $(\mathbf{A}^T)^T = \mathbf{A}$
b. $(\mathbf{A}+\mathbf{B})^T= \mathbf{A}^T + \mathbf{B}^T$
c. $(\alpha\mathbf{A})^T = \alpha\mathbf{A}^T$
d. $(\mathbf{A}\mathbf{B})^T = \mathbf{B}^T\mathbf{A}^T$ (NOT $\mathbf{A}^T\mathbf{B}^T$)

## Matrix Multiplication
\begin{tikzpicture}[>=latex]
% les matrices
\matrix (A) [matrix of math nodes,%
             nodes = {node style ge},%
             left delimiter  = (,%
             right delimiter = )] at (0,0)
{%
  a_{11} & a_{12} & \ldots & a_{1p}  \\
  |[node style sp]| a_{21}%
         & |[node style sp]| a_{22}%
                  & \ldots%
                           & |[node style sp]| {a_{2p}}; \\
  \vdots & \vdots & \ddots & \vdots  \\
  a_{n1} & a_{n2} & \ldots & a_{np}  \\
};
\node [draw,below=10pt] at (A.south) 
    { $A$ : \textcolor{red}{$n$ rows} $p$ columns};

\matrix (B) [matrix of math nodes,%
             nodes = {node style ge},%
             left delimiter  = (,%
             right delimiter =)] at (6*\myunit,6*\myunit)
{%
  b_{11} & |[node style sp]| b_{12}%
                  & \ldots & b_{1q}  \\
  b_{21} & |[node style sp]| b_{22}%
                  & \ldots & b_{2q}  \\
  \vdots & \vdots & \ddots & \vdots  \\
  b_{p1} & |[node style sp]| b_{p2}%
                  & \ldots & b_{pq}  \\
};
\node [draw,above=10pt] at (B.north) 
    { $B$ : $p$ rows \textcolor{red}{$q$ columns}};
% matrice résultat
\matrix (C) [matrix of math nodes,%
             nodes = {node style ge},%
             left delimiter  = (,%
             right delimiter = )] at (6*\myunit,0)
{%
  c_{11} & c_{12} & \ldots & c_{1q} \\
  c_{21} & |[node style sp,red]| c_{22}%
                  & \ldots & c_{2q} \\
  \vdots & \vdots & \ddots & \vdots \\
  c_{n1} & c_{n2} & \ldots & c_{nq} \\
};
% les fleches
\draw[blue] (A-2-1.north) -- (C-2-2.north);
\draw[blue] (A-2-1.south) -- (C-2-2.south);
\draw[blue] (B-1-2.west)  -- (C-2-2.west);
\draw[blue] (B-1-2.east)  -- (C-2-2.east);
\draw[<->,red](A-2-1) to[in=180,out=90]
    node[arrow style mul] (x) {$a_{21}\times b_{12}$} (B-1-2);
\draw[<->,red](A-2-2) to[in=180,out=90]
    node[arrow style mul] (y) {$a_{22}\times b_{22}$} (B-2-2);
\draw[<->,red](A-2-4) to[in=180,out=90]
    node[arrow style mul] (z) {$a_{2p}\times b_{p2}$} (B-4-2);
\draw[red,->] (x) to node[arrow style plus] {$+$} (y)%
                  to node[arrow style plus] {$+\raisebox{.5ex}{\ldots}+$} (z)%
                  to (C-2-2.north west);
\node [draw,below=10pt] at (C.south) 
    {$ C=A\times B$ : \textcolor{red}{$n$ rows}  \textcolor{red}{$q$ columns}};
\end{tikzpicture}
- Source : Alain Matthes, http://altermundus.com/pages/examples.html

## Multiplication Rules

$\mathbf{A} = (a_{ij})_{m\times n}$ and $\mathbf{B} = (b_{ij})_{m\times n}$ and 
$\mathbf{C} = (c_{ij})_{m\times n}$ are $m\times n$ matrices, and $\delta$, $\alpha$ and $\beta$ are scalars (real numbers).

- $\mathbf{A} + \mathbf{B} = (a_{ij}+b_{ij})_{m\times n}$
- $\delta \mathbf{A} = (\delta a_{ij})_{m\times n}$
- $\mathbf{A} + \mathbf{B} = \mathbf{B} + \mathbf{A}$
- $(\mathbf{A} + \mathbf{B}) + \mathbf{C} = \mathbf{A} + (\mathbf{B} + \mathbf{C})$
- $(\alpha + \beta)\mathbf{A} = \alpha\mathbf{A} + \beta\mathbf{A}$
- $\alpha(\mathbf{A} + \mathbf{B}) = \alpha\mathbf{A} + \alpha\mathbf{B}$
- $\mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A}$, in most cases.
- $(\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C})$
- $(\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C})$

## Cramer's rule for $2 \times 2$ matrices

$$
    \mathbf{A}=    
    \begin{bmatrix} 
        a_{11}    &  a_{12}    \\
        a_{21}    &  a_{22}    \\
    \end{bmatrix}
    , \mathbf{b}=
    \begin{bmatrix}
       b_1  \\
       b_2  \\
    \end{bmatrix}
$$

- The unknown values of $x_1$ and $x_2$ can be shown to be equal to
$$
x_1 = 
\frac{
            \begin{vmatrix} 
                b_1    &  a_{12}    \\
                b_2    &  a_{22}    \\
            \end{vmatrix}}{|A|},
x_2 = 
\frac{
            \begin{vmatrix} 
                a_{11}    &  b_1    \\
                a_{21}    &  b_2    \\
            \end{vmatrix}}{|A|}
$$

### The determinant of $\mathbf{A}$ is:

$$
    |\mathbf{A}|=    
    \begin{vmatrix} 
        a_{11}    &  a_{12}    \\
        a_{21}    &  a_{22}    \\
    \end{vmatrix}
    =
$$

$$
a_{11}\cdot a_{22} - (a_{21}\cdot a_{12})
$$

### Thus:
$$
x_1 = 
\frac{
            \begin{vmatrix} 
                b_1    &  a_{12}    \\
                b_2    &  a_{22}    \\
            \end{vmatrix}}{
            \begin{vmatrix} 
                a_{11}    &  a_{12}    \\
                a_{21}    &  a_{22}    \\
            \end{vmatrix}
            },
x_2 = 
\frac{
            \begin{vmatrix} 
                a_{11}    &  b_1    \\
                a_{21}    &  b_2    \\
            \end{vmatrix}}{
            \begin{vmatrix} 
                a_{11}    &  a_{12}    \\
                a_{21}    &  a_{22}    \\
            \end{vmatrix}
            }
$$

