---
title: "Mathematics for Economics: Semester 1"
author: "Rob Smith"
date: "Updated `r format(Sys.time(), '%B %d, %Y')`"
output:
  beamer_presentation:
    theme: "Berkeley"
    colortheme: "seahorse"
    fonttheme: "serif"
    slide_level: 3
  bookdown::gitbook:
    config:
      toc:
        collapse: section
    self.contained: yes
    split_by: none
urlcolor: red
header-includes: 
  - \usepackage{tikz}
  - \usepackage{pgfplots}
  - \usepackage{fontawesome5}
  - \usepackage{academicons}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include=FALSE)
```

# Linear Algebra: Vectors and Matrices

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New section %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New section %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

## Motivations
### Why learn about Matrices??
#### What are they good for?
- The red text in these slides are all links to videos that you can watch.
- How we figure out how to move around in the space around us (the geometric understanding)
- [This geometric understanding is really powerful, and very helpful in understanding matrix operations!](https://www.youtube.com/watch?v=kjBOesZCoqc&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab)

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### Some cool applications
- [3D rendering of objects (nothing to do with this course, but very cool)](https://www.youtube.com/watch?v=KdyvizaygyY&list=PLzH6n4zXuckrPkEUK5iMQrQyvj9Z6WCrm)
- They are also pretty amazing for solving systems of equations.
- This turns out to be pretty useful when you are working with large economic models!

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### The good stuff - Economics
- Economic models normally involve some system of equations.
- We can use matrix operations to solve them!!
- A glimpse into the future of what we want to be able to do...

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### The course in an image
\begin{tikzpicture}[sibling distance=5em,
                    every node/.style = {shape=rectangle, rounded corners,
                    draw, align=center,
                    top color=white, bottom color=blue!20}]]
    \node {Solve a Model}
    child {node {Inverse}
        child {node {Ident.}}
        child {node {Adj.}}
        child {node {Det.}
            child {node {Add}
                child {node {Scalar / Vector}}}
            child {node {Subtr.}}
            child {node {Multi.}
                child {node {Scalar / Vector}}}
            child {node {Transp.}}}};
\end{tikzpicture}

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### Where all of this is going...
- Linear algebra and systems of equations
- A generic way to represent a system of equations is:
    $$\begin{matrix}
        a_{11}x_1 + & a_{12}x_2 & + & a_{13}x_3 & + & \dots & + & a_{1n}x_n & = & b_1\\
        a_{21}x_1 + & a_{22}x_2 & + & a_{23}x_3 & + & \dots & + & a_{2n}x_n & = & b_2\\
        \vdots & \vdots & & \vdots & & \ddots & & \vdots & & \vdots \\
        a_{m1}x_1 + & a_{m2}x_2 & + & a_{m3}x_3 & + & \dots & + & a_{mn}x_n & = & b_m
    \end{matrix}$$
- $a_{11}$ through $a_{mn}$ are *coefficients* of the system of equations
- Each $x$ value is a different *component* or *variable*.

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### As a system
- That system can be re-represented using matrices and vectors as:
$$
    \begin{bmatrix}
        a_{11} & a_{12} & a_{13} & \dots & a_{1n}\\
        a_{21} & a_{22} & a_{23} & \dots & a_{2n}\\
        \vdots & \vdots & \vdots & \ddots & \vdots\\
        a_{m1} & a_{m2} & a_{m3} & \dots & a_{mn}
    \end{bmatrix}
    \cdot
    \begin{bmatrix}
        x_1\\
        x_2\\
        \vdots\\
        x_n
    \end{bmatrix} =
    \begin{bmatrix}
        b_1\\
        b_2\\
        \vdots\\
        b_m
    \end{bmatrix}
$$

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### But first, the foundations!!
#### What are matrices and vectors?

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New section %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New section %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

## Matrices and vectors: Foundations
### What is Matrix?
- Just a **very useful** and **very powerful** way to store information.
- Matrices are always denoted with a **bold** letter, such as **A**, **B**, or **M**.
- [Khan Academy: Pre-calculus course on matrices](https://www.khanacademy.org/math/precalculus/precalc-matrices)
- [Khan Academy: Introduction what is a matrix??](https://www.youtube.com/watch?v=0oGJTQCy4cQ&list=PLGR_7q6BJHQFbTCW995GhRY1AwWuWOvBH&index=1)

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### Conventions
- By convention, we note $rows (m)$ first and then $columns (n)$, so matrix $\mathbf{A}$ is an $m \times n$ matrix
$$
\mathbf{M}=
    \begin{bmatrix}
        1 & 2 & 3 & 4 & 5 \\
        3 & 4 & 5 & 6 & 7
    \end{bmatrix}
$$
- Matrix $\mathbf{M}$ has 2 rows, and 5 columns. $\mathbf{M}$ is a $2 \times 5$ matrix.
- [Example, data in a matrix](https://www.youtube.com/watch?v=PPOIlLhsT6s&list=PLGR_7q6BJHQFbTCW995GhRY1AwWuWOvBH&index=2)
- Each number in the matrix is called an *element*.

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### Examples
#### What do they look like?
- Matrix 
$$
\mathbf{A}=
    \begin{bmatrix}
        1 & 2 & 3 \\
        3 & 4 & 5
    \end{bmatrix}
$$

- Row vector
$$
\mathbf{b}=
    \begin{bmatrix}
        1 & 2 & 3
    \end{bmatrix}
$$

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### ...continued
- Column vector
$$
\mathbf{f}=
    \begin{bmatrix}
        1\\
        8\\
        9
    \end{bmatrix}
$$
- Notice that all vectors are labelled with a small **bold** 
letter (lower-case) and all matrices with a capital 
**bold** letter (upper-case).

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New section %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New section %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

## Scalar and vector operations
### Basic operations
#### Scalar multiplication, addition and subtraction
- [Scalar and matrix multiplication](https://www.youtube.com/watch?v=TbaltFbJ3wE&index=3&list=PLGR_7q6BJHQFbTCW995GhRY1AwWuWOvBH)
- Scalars are just numbers. To multiply a matrix by a number (scalar), just multiply each element by that number!
- When used for multiplication this can be imagined as a number that you will use to "scale" each entry of a matrix up or down.

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### The commutative and associative laws
- If $x$ is a scalar (number), and $\mathbf{A}$ is a matrix, then $$x \times \mathbf{A} = \mathbf{A} \times x$$
- Or simply, $x\mathbf{A} = \mathbf{A}x$, thus **scalar multiplication** IS commutative.
- When used for addition or subtraction, scalars can be imagined as simple numbers, to be added or subtracted from each of the entries in a matrix.
- Therefore, the order does not matter too much. $$x + \mathbf{A} = \mathbf{A} + x$$, and $$\mathbf{A} - x = -x + \mathbf{A}$$
- Scalar addition, subtraction and multiplication *ARE ALL* commutative and associative.

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New section %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New section %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

## Matrices: Basic operations
### Addition and subtraction
- [Addition and subtraction of matrices](https://www.youtube.com/watch?v=WR9qCSXJlyY&index=4&list=PLGR_7q6BJHQFbTCW995GhRY1AwWuWOvBH)
- !!! You can only add or subtract matrices if they are exactly the same shape / size !!!
- I.e. A 3x3 matrix can only be added to another 3x3 matrix! The same for subtraction.
- Simply add or subtract the corresponding *elements* (or *entries*).

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### Addition and subtraction rules
- To add two matrices, simply add the values of each entry of the exact same locations in the each matrix.
- Also, $$\mathbf{A} + \mathbf{B} = \mathbf{B} + \mathbf{A}$$
- As with simple algebra, subtraction is the same as multiplying one of the matrices by $(-1)$, which is a scalar. Therefore 
$$\mathbf{A} - \mathbf{B} = (-1)\mathbf{B} + \mathbf{A}$$
- Because we know that scalar multiplication ordering is not important (stated differently: it is commutative).

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### Some simple exercises to try
1.  Find $\mathbf{A} + \mathbf{B}$, for 
$$
\mathbf{A}=
    \begin{bmatrix}
        1 & 2 & 3 \\
        3 & 4 & 5
    \end{bmatrix}
, and \quad \mathbf{B}=
    \begin{bmatrix}
        1 & 2 & 3 \\
        3 & 4 & 5
    \end{bmatrix}
$$

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### Exercises continued
2. Find $\mathbf{A} - \mathbf{B}$, for
$$
\mathbf{A}=
    \begin{bmatrix}
        5 & 2\\
        3 & 4\\
        8 & 6
    \end{bmatrix}
, and, \mathbf{B}=
    \begin{bmatrix}
        \frac{3}{5} & 2\\
        3 & 4\\
        5 & \frac{1}{2}
    \end{bmatrix}
$$
3.  Find $x\mathbf{A}$, for
$$
x = \frac{1}{2}, and \quad \mathbf{A}=
    \begin{bmatrix}
        1 & 2 & 3 \\
        3 & 4 & 5
    \end{bmatrix}
$$

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New section %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New section %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

## Matrices: Transpose and data representation
### Taking the transpose
- [Transpose of a matrix](https://www.youtube.com/watch?v=TZrKrNVhbjI&index=5&list=PLGR_7q6BJHQFbTCW995GhRY1AwWuWOvBH)
- The transpose of matrix $\mathbf{A}$, can be written as $\mathbf{A}^{T}$
- Rows become columns! Therefore a matrix of order $3\times2$ will become a $2\times3$ matrix if we take the transpose.

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### Simple 2 x 3 example
$$
\mathbf{A}=
    \begin{bmatrix}
        5 & 2\\
        3 & 4\\
        8 & 6
    \end{bmatrix}
, \quad \mathbf{A}^T=
    \begin{bmatrix}
        5 & 3 & 8\\
        2 & 4 & 6
    \end{bmatrix}
$$
- Operations such as this are most easily understood when thinking in physical space, but the purpose will be clearer when we start to use operations like this one to solve systems of equations.

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### Exercises
1. Find the transpose of $\mathbf{A}$, for
$$
\mathbf{A}=
    \begin{bmatrix}
        7 & 14 & -13 \\
        1 & 2 & 3 \\
        2221 & 743 & 5
    \end{bmatrix}
$$

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### Exercises continued
2. Find the transpose of $\mathbf{A}$, plus $\mathbf{B}^{T}$, for
$$        
    \mathbf{A}=
        \begin{bmatrix}
            5 & 2\\
            3 & 4\\
            8 & 6
        \end{bmatrix}
    , and \quad \mathbf{B}=
        \begin{bmatrix}
            \frac{1}{3} & 2\\
            3 & 4\\
            5 & \frac{4}{5}
        \end{bmatrix}
$$
3. Find $x \times \mathbf{A}^{T}$, for
$$
    x = \frac{1}{2}, and \quad \mathbf{A}=
        \begin{bmatrix}
            a & 2 & v \\
            3 & z & 5
        \end{bmatrix}
$$


<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### Data representation exercise
1. There are cats and birds, cats have 4 legs, birds have 2. Cats have 20 claws, birds have 8. Cats eat once a day, birds eat 5 times.
2. Bob and Dave are friends. If each of them eat food, they gain wait differently. For each kilogram of food, Bob gains 400g, and Dave gains 600g. For each kilometre they run, they each lose weight differently. Bob loses 50g and Dave loses 85g. For each beer they drink, Bob gains 200g, and Dave gains 100g.

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### ... continued
3. X and Y are variables, lets call them Bob and Dave's weight. Both X and Y depend on eating ( a ), running ( b ) and beers ( c ). Write equations for these Bob and Dave's weight.
- We now have the coefficients of a system of simultaneous equations stored in a matrix... We'll get back to this!

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New section %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New section %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

## Matrices: Multiplication
### Conditions for valid multiplication
- When we multiply two matrices, we get the dimensions of the new matrix from the rows of the first matrix and the columns of the second.
- If, recall the order of a matrix is $m\times n$:
- $\mathbf{A}$ is of order $(2 \times 3)$, $(3 \times 4)$ are $\mathbf{B}$'s dimensions
- We know that we can multiply them because $n_A = m_B = 3$

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### Conditions for valid multiplication
- To work out the dimensions of the NEW matrix, after we multiply, we take the number of rows from $\mathbf{A} = m_A = 2$, and the columns from $\mathbf{B}= n_B=4$
- In matrix terms:
$$
\begin{bmatrix}
     & \mathbf{A} & \\
    (m_A & \times & n_A)
\end{bmatrix}
\times
\begin{bmatrix}
     & \mathbf{B} & \\
    (m_B & \times & n_B)
\end{bmatrix}
=
\begin{bmatrix}
     & \mathbf{AB} & \\
    (n_A & \times & m_B)
\end{bmatrix}
$$

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### When is it defined?
- [A first look at Matrix multiplication](https://www.youtube.com/watch?v=kT4Mp9EdVqs&index=6&list=PLGR_7q6BJHQFbTCW995GhRY1AwWuWOvBH)
- Matrix $\mathbf{A}=m_a\times n_a$, and matrix $\mathbf{B}=m_b\times n_b$, can only be multiplied if the number of columns in $\mathbf{A}$ equal the number of rows in $\mathbf{B}$.
- I.e. $\mathbf{AB}$ is only defined if: $n_a = m_b$
- And,  $\mathbf{BA}$ is only defined if: $n_b = m_a$

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### The dot product
- It is called the dot product. Think of $rows \times columns$
- **ORDER MATTERS**
- $$\mathbf{A} \times \mathbf{B} \neq \mathbf{B} \times \mathbf{A}$$, or simply, $$\mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A}$$
- [Multiplying a matrix by a vector](https://www.youtube.com/watch?v=Awcj447pYuk&list=PLGR_7q6BJHQFbTCW995GhRY1AwWuWOvBH&index=8) ($2\times 3 \cdot 3\times 1$), $\mathbf{Aw}$
- [Multiplying a matrix by a matrix](https://www.youtube.com/watch?v=OMA2Mwo0aZg&index=7&list=PLGR_7q6BJHQFbTCW995GhRY1AwWuWOvBH) ($2\times 3 \cdot 3\times 2$), $\mathbf{AB}$
- [Defined vs. undefined multiplication, some examples](https://www.youtube.com/watch?v=O1-9f1g0OsI&index=9&list=PLGR_7q6BJHQFbTCW995GhRY1AwWuWOvBH).

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### Exercises
1. If possible, find $\mathbf{A} \times \mathbf{B}$?, for
$$
\mathbf{A}=
  \begin{bmatrix}
    1 & 2 & 3 \\
    3 & 4 & 5
  \end{bmatrix}
  , and, \mathbf{B}=
  \begin{bmatrix}
    1 & 2 & 3 \\
    1 & 2 & 3 \\
    3 & 4 & 5
  \end{bmatrix}
$$

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### Exercises continued ...
2. If possible, find $\mathbf{A} \times \mathbf{B}$?, for
$$
\mathbf{A}=
  \begin{bmatrix}
    5 & 2\\
    3 & 4\\
    8 & 6
  \end{bmatrix}
  , and, \mathbf{B}=
  \begin{bmatrix}
    \frac{3}{5} & 2\\
    3 & 4\\
    5 & \frac{1}{2}
  \end{bmatrix}
$$
3. If possible, find $\mathbf{B} \times \mathbf{A}$?, for
$$
\mathbf{A}=
  \begin{bmatrix}
    5 & 2\\
    3 & 4\\
    c & 4
  \end{bmatrix}
  , and \quad \mathbf{B} =
  \begin{bmatrix}
    \frac{3}{5} & 2 & e34 & 900\\
    3 & 4 & g & 23\\
    5 & \frac{1}{2} & i43 & 12
  \end{bmatrix}
$$
4. For (3) above if possible find $\mathbf{B}^{T}\mathbf{A}?$

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### Matrix multiplication: Non-commutative rule
- [Matrix multiplication is NOT commutative!](https://www.youtube.com/watch?v=z-SU7P-gIoQ&index=10&list=PLGR_7q6BJHQFbTCW995GhRY1AwWuWOvBH)
- That means that **ORDER MATTERS**.
- As before, $$\mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A}$$

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### Summary of rules
$\mathbf{A} = (a_{ij})_{m\times n}$ and $\mathbf{B} = (b_{ij})_{m\times n}$ and 
$\mathbf{C} = (c_{ij})_{m\times n}$ are $m\times n$ matrices, and $\delta$, $\alpha$ and $\beta$ are scalars (real numbers).
- $\mathbf{A} + \mathbf{B} = (a_{ij}+b_{ij})_{m\times n}$
- $\delta \mathbf{A} = (\delta a_{ij})_{m\times n}$
- $\mathbf{A} + \mathbf{B} = \mathbf{B} + \mathbf{A}$
- $(\mathbf{A} + \mathbf{B}) + \mathbf{C} = \mathbf{A} + (\mathbf{B} + \mathbf{C})$
- $(\alpha + \beta)\mathbf{A} = \alpha\mathbf{A} + \beta\mathbf{A}$
- $\alpha(\mathbf{A} + \mathbf{B}) = \alpha\mathbf{A} + \alpha\mathbf{B}$
- $\mathbf{A}\mathbf{B} \neq \mathbf{B}\mathbf{A}$, in most cases.
- $(\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C})$
- $(\mathbf{A} + \mathbf{B})\mathbf{C} = \mathbf{A}\mathbf{C} + \mathbf{B}\mathbf{C})$

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### Matrix multiplication: Associative rule
- [Matrix multiplication IS associative](https://www.youtube.com/watch?v=8Ryfe82DTcM&index=11&list=PLGR_7q6BJHQFbTCW995GhRY1AwWuWOvBH)
- This means that as long as the order stays the same, the **sequence does NOT matter**! So, $$(\mathbf{A}\mathbf{B})\mathbf{C} = \mathbf{A}(\mathbf{B}\mathbf{C})$$

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New section %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New section %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

## The identity matrix
### Some simple algebraic comparisons
- In regular algebra, for any real number, $a\times 1 = 1$
- In matrices there is a similar concept, called
[The Identity Matrix](https://www.youtube.com/watch?time_continue=297&v=iUQR0enP7RQ) , denoted by $\mathbf{I}$.
- Like the number 1 in normal algebra, in matrices, $\mathbf{I} \times\mathbf{A} = \mathbf{A}$
- Also, $\mathbf{A} \times \mathbf{I} = \mathbf{A}$, but will the dimensions of $\mathbf{I}$ be the same?

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### An illustration
- To illustrate the concept, we will find the identity matrix for:
$$
\mathbf{A}=
\begin{bmatrix}
    5 & 2 & 9\\
    3 & 4 & 1\\
    c & 4 & 7
\end{bmatrix}
$$

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### How should it look and how does it work?
- Using matrix multiplication rules, rows by columns:
$$
\mathbf{I}
    \begin{bmatrix}
        ? & ? & ?\\
        ? & ? & ?\\
        ? & ? & ?
    \end{bmatrix}
    \times \quad \mathbf{A}
    \begin{bmatrix}
        5 & 2 & 9\\
        3 & 4 & 1\\
        c & 4 & 7
    \end{bmatrix}
    = \mathbf{IA}=
    \begin{bmatrix}
        5 & 2 & 9\\
        3 & 4 & 1\\
        c & 4 & 7
    \end{bmatrix}
$$
- What would that *Identity Matrix* need to look like?
- Think back to **vector multiplication**...

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### It is actually quite simple
- $\mathbf{I}$ for any matrix can therefore be found VERY easily.
- We only need to know the order of the matrix for which we want the identity matrix.
- Think about how the dot(.)product works in matrix multiplication.
- Each column by each row, to get each element of the final product.
- We want all values except 1 in each row/column to be zero. We just need the value to be in the right place!

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### What does this look like?
$$
\mathbf{I}_2 =
    \begin{bmatrix}
        1 & 0\\
        0 & 1
    \end{bmatrix}
    , \quad \mathbf{I}_3 =
    \begin{bmatrix}
        1 & 0 & 0\\
        0 & 1 & 0\\
        0 & 0 & 1
    \end{bmatrix}
    , \quad \mathbf{I}_4 =
    \begin{bmatrix}
        1 & 0 & 0 & 0\\
        0 & 1 & 0 & 0\\
        0 & 0 & 1 & 0\\
        0 & 0 & 0 & 1
    \end{bmatrix}
$$
$$
\mathbf{I}_n =
    \begin{bmatrix}
        1       & 0         & 0         & \dots     & 0\\
        0       & 1         & 0         & \dots     & 0\\
        0       & 0         & 1         & \dots     & 0\\
        \vdots  & \vdots    & \vdots   & \ddots    & \vdots\\
        0       & 0         & 0         & \dots     & 1
    \end{bmatrix}
$$

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### To calculate the dimensions (or, *n*)
#### Essentially a square matrix with "1"s down the main diagonal
- To calculate the [dimensions](https://www.youtube.com/watch?v=l7p1X5pdDoc&list=PLGR_7q6BJHQFbTCW995GhRY1AwWuWOvBH&index=14),
we must remember how multiplication works.

#### If we know the end result, then we can work out the origins:
$$
    \begin{bmatrix}
         & \mathbf{I} &\\
        (? & \times & ?)
    \end{bmatrix} \times
    \begin{bmatrix}
         & \mathbf{B} &\\
        (2 & \times & 4)
    \end{bmatrix} = 
    \begin{bmatrix}
         & \mathbf{B} &\\
        (2 & \times & 4)
    \end{bmatrix}
$$

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### Identify the dimensions of **I**
- We know that the dimensions of $\mathbf{B}$ must stay the same. We also know where to find the number of rows and columns of the final product.
- Recall that:
$$
    \begin{bmatrix}
         & \mathbf{A} &\\
        (m_A & \times & n_A)
    \end{bmatrix} \times
    \begin{bmatrix}
         & \mathbf{B} &\\
        (m_B & \times & n_B)
    \end{bmatrix} = 
    \begin{bmatrix}
         & \mathbf{AB} &\\
        (m_A & \times & n_B)
    \end{bmatrix}
$$
- Try to work it out, replacing A with I.

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### Identify the dimensions of **I**
- From multiplication, the number of rows in $\mathbf{IB}$ must come from $\color{blue}{m_\mathbf{I}}$
- We also know they must be the same as in $\mathbf{B}$, so $\color{blue}{m_\mathbf{I}} = \color{blue}{m_\mathbf{IB}} = \color{red}{m_\mathbf{B}}$.
- From multiplication, we also know that $\mathbf{IB}$ is only defined if $\color{red}{n_\mathbf{I}}=\color{red}{m_\mathbf{B}}$
- Therefore, the number of columns in $\mathbf{I}$ must equal number of rows in $\mathbf{B}$
- So, $\color{red}{n_\mathbf{I}} = \color{blue}{m_\mathbf{B}}$
$$
\begin{bmatrix}
     & \mathbf{I} &\\
    (\color{blue}{a} & \times & \color{red}{a})
\end{bmatrix} \times
\begin{bmatrix}
     & \mathbf{B} &\\
    (\color{red}{a} & \times & b)
\end{bmatrix} = 
\begin{bmatrix}
     & \mathbf{IB} = \mathbf{B} &\\
    (\color{blue}{a} & \times & b)
\end{bmatrix}
$$


<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### Identify the dimensions of **I**
- This means that the identity matrix has exactly the same number of rows as it has columns.
- The identity matrix is therefore always **a square matrix**.
- We denote a $2 \times 2$ identity matrix as $\mathbf{I}_2$
- In the general example above, The identity matrix is therefore $\mathbf{I}_a$
- We also know that the **order matters!!!!**


<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### Identify the dimensions of **I**: Changing the order
#### Most Importantly, $\mathbf{I} \approx 1$
- Therefore, in terms of scalar multiplication $$\mathbf{IB} = 1\times \mathbf{B}$$
- Thus,
$$\mathbf{IB} = \mathbf{BI} = 1\times \mathbf{B} = \mathbf{B}\times 1 = \mathbf{B}$$

#### Thought Exercise
- Try to find the general rule for the identity matrix for $\mathbf{BI}$.
$$
\begin{bmatrix}
        & \mathbf{B}    &       \\
    (a  & \times        &   b)
\end{bmatrix}
\times
\begin{bmatrix}
        & \mathbf{I}    &       \\
    (?  & \times        &   ?)
\end{bmatrix} = 
\begin{bmatrix}
        & \mathbf{BI} = \mathbf{B}  &       \\
    (?  & \times                    &   ?)
\end{bmatrix}
$$

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### Identify the dimensions of **I**: Changing the order
- From multiplication, the number of rows in $\mathbf{BI}$ must come from $m_\mathbf{B}$.
- To work out what $\mathbf{I}$'s dimensions are we can again get them from the final result. This time, $\color{blue}{n_\mathbf{BI}} = \color{blue}{n_\mathbf{I}}$, but to get $\mathbf{BI}=\mathbf{B}$, it must also be true that $\color{blue}{n_\mathbf{BI}} = \color{red}{n_\mathbf{B}}$, and therefore, $\color{blue}{n_\mathbf{I}} = \color{blue}{n_\mathbf{BI}} = \color{red}{n_\mathbf{B}}$.
- From multiplication, we know that $\mathbf{BI}$ is only defined if $\color{red}{n_\mathbf{B}}=\color{red}{m_\mathbf{I}}$.

### ... continued
- Therefore, the number of rows in $\mathbf{I}$ must equal number of columns in $\mathbf{B}$.
- So, $\color{red}{n_\mathbf{B}} = \color{red}{m_\mathbf{I}}$.
$$
\begin{bmatrix}
     & \mathbf{B} &\\
    (a & \times & \color{red}{b})
\end{bmatrix} \times
\begin{bmatrix}
     & \mathbf{I} &\\
    (\color{red}{b} & \times & \color{blue}{b})
\end{bmatrix} =
\begin{bmatrix}
     & \mathbf{BI} = \mathbf{B} &\\
    (a & \times & \color{blue}{b})
\end{bmatrix}
$$
- For the new ordering of the multiplication, the identity matrix is therefore $\mathbf{I}_b$.
#### What matters is that the result is the same!!
$$\mathbf{IB} = \mathbf{BI} = \mathbf{B}$$

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### Exercises
1. Find the identity matrix for $\mathbf{IF}$, for
$$
\mathbf{F}=
  \begin{bmatrix}
    1 & 2 & 3 \\
    1 & 2 & 3 \\
    3 & 4 & 5
  \end{bmatrix}
$$
2. Find the identity matrix for $\mathbf{G}$, for $\mathbf{IG}$, where
$$
\mathbf{G}=
    \begin{bmatrix}
        266 & 2 & 9 & 65 & 1\\
        72 & 45 & 6n & 0 & 40\\
        \frac{3}{r} & 6 & 44 & 26 & 12\\
        11 & 3t & a & 4442 & \frac{n}{22}\\
        73 & 88 & 117 & 563 & 1
    \end{bmatrix}
$$

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### Exercises continued...
3. Find the identity matrix for $\mathbf{AC}$, for $\mathbf{(AC)I}$, where
$$
\mathbf{A}=
    \begin{bmatrix}
        5 & 2 & 23\\
        3 & 4 & 3v\\
        c & 4 & 886
    \end{bmatrix}
, and \quad \mathbf{C} =
    \begin{bmatrix}
        \frac{3}{5} & 2 & e34 & 900\\
        3 & 4 & g & 23\\
        5 & \frac{1}{2} & i43 & 12
    \end{bmatrix}
$$

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New section %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New section %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

## The zero matrix
### Algebraic comparisons
- In standard algebra we can multiply a real number by zero, and the result is 0. So, $$a \times 0 = 0$$
- Again we can do something similar with matrices, called the [zero matrix](https://www.youtube.com/watch?v=LOf8bfjiLow&list=PLGR_7q6BJHQFbTCW995GhRY1AwWuWOvBH&index=15).
- The difference: this time we want a matrix the same size as we started out with, but with all values equal to zero.
- We denote the zero matrix as a bold zero, $\mathbf{0}$. So in matrix terms, matrix $$\mathbf{A} \times  \mathbf{0} = \mathbf{0}$$
- What dimensions do you expect the zero matrix to have?

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### Usefulness and dimensions
- What is most important is understanding the operation. Where, $$\mathbf{B} \times  \mathbf{0} = \mathbf{0}$$, and $$\mathbf{0} \times  \mathbf{A} = \mathbf{0}$$, and $$\mathbf{AB} \times  \mathbf{0} = \mathbf{0}$$
- In terms of dimensions, we can just use a square matrix (like the identity matrix), but just make all elements equal to "0".

<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->
<!-- %%%%%%%%%%%%%%%%%%%%%%%%% New slide %%%%%%%%%%%%%%%%%%%%%%%%%%%%% -->

### Usefulness and dimensions
- But, the zero matrix used in multiplication does not need to be square. It only needs to satisfy the rules of matrix multiplication. $$n_A = m_B$$
- The dimensions of the resulting zero matrix will then depend on original matrix and the size chosen for the zero matrix.